class TEXTS:
    ABOUT_SONG = (
        "**ᴛɪᴛʟᴇ:** __{0}__ \n\n"
        "**ᴄʜᴀɴɴᴇʟ:** __{1}__ \n"
        "**ᴘᴜʙʟɪsʜᴇᴅ:** __{2}__ \n"
        "**ᴠɪᴇᴡs:** __{3}__ \n"
        "**ᴅᴜʀᴀᴛɪᴏɴ:** __{4}__ \n\n"
        "**❆** {5}"
    )
    ABOUT_USER = (
        "**✘ ᴛᴏᴘ ᴜsᴇʀ ɪɴғᴏ:**\n\n"
        "**💬 ɴᴀᴍᴇ:** {0}\n"
        "**💠 ɪᴅ:** `{1}`\n"
        "**⚜️ ʟᴇᴠᴇʟ:** __{2}__\n"
        "**🎶 sᴏɴɢs ᴘʟᴀʏᴇᴅ:** __{3}__\n"
        "**〥 ᴊᴏɪɴᴇᴅ sɪɴᴄᴇ:** __{4}__\n\n"
        "**❆** {5}"
    )
    BOOTED = (
        "#sᴛᴀʀᴛ\n\n"
        "**{0} ɪs ᴀʟɪᴠᴇ!**\n\n"
        "__» ᴘʙx-ᴍᴜsɪᴄ ᴠᴇʀsɪᴏɴ:__ `{1}`\n"
        "__» ᴘʏᴛʜᴏɴ ᴠᴇʀsɪᴏɴ:__ `{2}`\n"
        "__» ᴘʏʀᴏɢʀᴀᴍ ᴠᴇʀsɪᴏɴ:__ `{3}`\n"
        "__» ᴘʏᴛɢᴄᴀʟʟs ᴠᴇʀsɪᴏɴ:__ `{4}`\n\n"
        "**</>** {5}"
    )
    PING_REPLY = (
        "**📌 ᴘɪɴɢᴇᴅ ʙᴏᴛ sᴇʀᴠᴇʀ!**\n\n"
        "**🏁 sᴘᴇᴇᴅ:** __{0} ᴍs__\n"
        "**⏳ ᴜᴘᴛɪᴍᴇ:** __{1}__\n"
        "**🎶 ᴠᴄ ᴘɪɴɢ:** __{2} ᴍs__"
    )
    PLAYING = (
        "**💫 ɴᴏᴡ ᴘʟᴀʏɪɴɢ....🌸** \n\n"
        "**🎧 ᴛɪᴛʟᴇ :** [{1}]({4})\n"
        "**⏱️ ᴅᴜʀᴀᴛɪᴏɴ :** __{2}__\n"
        "**🥀 ʀᴇǫᴜᴇsᴛᴇʀ :** {3}"
    )
    PROFILE = (
        "**{0}\nᴜsᴇʀ ᴘʀᴏғɪʟᴇ**\n\n"
        "**💬 ɴᴀᴍᴇ:** {1}\n"
        "**💠 ɪᴅ:** `{2}`\n"
        "**📝 ᴜsᴇʀ ᴛʏᴘᴇ:** __{3}__\n"
        "**⚜️ ʟᴇᴠᴇʟ:** __{4}__\n"
        "**🎶 sᴏɴɢs ᴘʟᴀʏᴇᴅ:** __{5}__\n"
        "**〥 ᴊᴏɪɴᴇᴅ sɪɴᴄᴇ:** __{6}__\n\n"
        "**❆** {7}"
    )
    QUEUE = (
        "**✨ ǫᴜᴇᴜᴇ ᴘᴏsɪᴛɪᴏɴ.... (#{0})** \n\n"
        "**🎧 sᴏɴɢ :** __{1}__\n"
        "**🕚 ᴅᴜʀᴀᴛɪᴏɴ :** __{2}__\n"
        "**🥀 ʀᴇǫᴜᴇsᴛᴇʀ :** {3}"
    )
    SONG_CAPTION = (
        "**⊸ ᴛɪᴛʟᴇ:** [{0}]({1})\n\n"
        "**⊸ ᴠɪᴇᴡs:** {2}\n"
        "**⊸ ᴅᴜʀᴀᴛɪᴏɴ:** {3}\n"
        "**⊸ ʀᴇᴏᴜᴇsᴛᴇᴅ ʙʏ:** {4}\n\n"
        "**❆** {5}"
    )
    SOURCE = (
        "**sᴏᴜʀᴄᴇ 📦:**\n\n"
        "**ɴᴏᴛᴇ:** \n__» ᴛʜᴇ sᴏᴜʀᴄᴇ ᴄᴏᴅᴇ ɪs ᴀᴠᴀɪʟᴀʙʟᴇ ᴏɴ ɢɪᴛʜᴜʙ. ʏᴏᴜ ᴄᴀɴ ғɪɴᴅ ᴛʜᴇ ʟɪɴᴋ ʙᴇʟᴏᴡ.__\n"
        "__» ᴇᴠᴇʀʏ ᴘʀᴏᴊᴇᴄᴛ ᴀᴠᴀɪʟᴀʙʟᴇ ᴜɴᴅᴇʀ ʙᴀᴅʜᴀᴄᴋᴇʀ98 ᴀʀᴇ ᴏᴘᴇɴ-sᴏᴜʀᴄᴇ ᴀɴᴅ ғʀᴇᴇ ᴛᴏ ᴜsᴇ ᴀɴᴅ ᴍᴏᴅɪғʏ ᴛᴏ ʏᴏᴜʀ ɴᴇᴇᴅs.__\n"
        "__» ᴀɴʏᴏɴᴇ ᴘʀᴇᴛᴇɴᴅɪɴɢ ᴛᴏ ʙᴇ ᴛʜᴇ ᴅᴇᴠᴇʟᴏᴘᴇʀ ᴏғ ᴛʜɪs ʙᴏᴛ ᴀɴᴅ sᴇʟʟɪɴɢ ᴛʜᴇ ᴄᴏᴅᴇ, ɪs ᴀ sᴄᴀᴍᴍᴇʀ.__\n\n"
        "__» ᴘʟᴇᴀsᴇ ᴄᴏɴsɪᴅᴇʀ ɢɪᴠɪɴɢ ᴀ sᴛᴀʀ ᴛᴏ ᴛʜᴇ ʀᴇᴘᴏsɪᴛᴏʀʏ ɪғ ʏᴏᴜ ʟɪᴋᴇᴅ ᴛʜᴇ ᴘʀᴏᴊᴇᴄᴛ.__\n"
        "__» ғᴇᴇʟ ғʀᴇᴇ ᴛᴏ ᴄᴏɴᴛᴀᴄᴛ ᴜs ɪғ ʏᴏᴜ ɴᴇᴇᴅ ᴀɴʏ ʜᴇʟᴘ ʀᴇɢᴀʀᴅɪɴɢ ᴛʜᴇ sᴏᴜʀᴄᴇ ᴄᴏᴅᴇ.__\n\n"
        "❤️🎶 {0}"
    )
    STATS = (
        "**⤞ sᴇʀᴠᴇʀ sᴛᴀᴛs:**\n"
        "    __ᴛᴏᴛᴀʟ ᴜsᴇʀs:__ `{0} ᴜsᴇʀs`\n"
        "    __ᴛᴏᴛᴀʟ ᴄʜᴀᴛs:__ `{1} ᴄʜᴀᴛs`\n"
        "    __ᴛᴏᴛᴀʟ ɢʙᴀɴs:__ `{2} ᴜsᴇʀs`\n"
        "    __ʙʟᴏᴄᴋᴇᴅ ᴜsᴇʀs:__ `{3} ᴜsᴇʀs`\n"
        "    __sᴏɴɢs ᴘʟᴀʏᴇᴅ:__ `{4} sᴏɴɢs`\n"
        "    __ᴀᴄᴛɪᴠᴇ ᴠᴄ:__ `{5} ᴠᴄ`\n\n"
        "**⤞ sʏsᴛᴇᴍ sᴛᴀᴛs:**\n"
        "    __ᴄᴏʀᴇ:__ `{6} ᴄᴏʀᴇs`\n"
        "    __ᴄᴘᴜ ᴜsᴀɢᴇ:__ `{7}`\n"
        "    __ᴅɪsᴋ ᴜsᴀɢᴇ:__ `{8}`\n"
        "    __ʀᴀᴍ ᴜsᴀɢᴇ:__ `{9}`\n"
        "    __ᴜᴘᴛɪᴍᴇ:__ `{10}`\n\n"
        "**</>** {11}"
    )
    SYSTEM = (
        "**⤞ sʏsᴛᴇᴍ ɪɴғᴏ:**\n\n"
        "   __ᴄᴏʀᴇ:__ `{0} ᴄᴏʀᴇs`\n"
        "   __ᴄᴘᴜ ᴜsᴀɢᴇ:__ `{1}`\n"
        "   __ᴅɪsᴋ ᴜsᴀɢᴇ:__ `{2}`\n"
        "   __ʀᴀᴍ ᴜsᴀɢᴇ:__ `{3}`\n"
        "   __ᴜᴘᴛɪᴍᴇ:__ `{4}`\n\n"
        "**</>** {5}"
    )
    HELP_ADMIN = (
        "**AUTHORIZED USERS COMMANDS:**\n\n"
        "**» /auth ; /unauth**\n"
        "    __Authorize or unauthorize user to use admins command such as /skip, /pause, etc.__\n\n"
        "**» /authlist**\n"
        "    __List all authorized users.__\n\n"
        "**» /authchat**\n"
        "    __This enables all the users in the chat to use admins command such as /skip, /pause, etc.__\n\n"
        "**» /mute ; /unmute**\n"
        "    __Mute or unmute the ongoing track in the voice chat.__\n\n"
        "**» /pause ; /resume**\n"
        "    __Pause or resume the ongoing track in the voice chat.__\n\n"
        "**» /stop ; /end**\n"
        "    __Stop the ongoing track in the voice chat.__\n\n"
        "**» /loop**\n"
        "    __Loop the playing track in the voice chat. Use [/loop 0] to disable the loop.__\n\n"
        "**» /skip**\n"
        "    __Skip the playing track in the voice chat.__\n\n"
        "**» /replay**\n"
        "    __Replay from the beginning of the playing track in the voice chat.__\n\n"
        "**» /seek**\n"
        "    __Seek the playing track in the voice chat. Use [/seek 10] to seek forward and [/seek-10] to seek backwards.__\n\n"
        "**» /clean**\n"
        "    __Clear the queue when bot seems to be bugged.__\n\n"
    )
    HELP_USER = (
        "**NORMAL USERS COMMANDS:**\n\n"
        "**» /play ; /vplay**\n"
        "    __Play replied audio/video file or YouTube video or searched query on voice chat.__\n\n"
        "**» /fplay ; /fvplay**\n"
        "    __Force play replied audio/video file or YouTube video or searched query on voice chat.__\n\n"
        "**» /bass ; /speed**\n"
        "    __Stream a song with bass-boosted or speed-boosted effects on voice chat.__\n\n"
        "**» /bs**\n"
        "    __Reply to an audio file to generate a bass-boosted version of the song.__\n\n"
        "**» /favs ; /myfavs ; /favorites**\n"
        "    __Show your favorite songs list.__\n\n"
        "**» /delfavs**\n"
        "    __Delete your favorite songs from your list.__\n\n"
        "**» /current ; /playing**\n"
        "    __Show the current playing song.__\n\n"
        "**» /queue ; /que ; /q**\n"
        "    __Show the queued songs list.__\n\n"
        "**» /song**\n"
        "    __Download the searched song from YouTube.__\n\n"
        "**» /lyrics**\n"
        "    __Get the lyrics of the searched song. Give artist name after ' - ' for accurate results. [/lyrics without me - eminem]__\n\n"
        "**» /profile ; /me**\n"
        "    __Show your profile and stats.__\n\n"
    )
    HELP_SUDO = (
        "**SUDO USERS COMMANDS:**\n\n"
        "**» /active**\n"
        "    __Check active voice chats of the bot.__\n\n"
        "**» /autoend**\n"
        "    __Enable or disable autoend inactive voice chats.__\n\n"
        "**» /block ; /unblock**\n"
        "    __Block or unblock user from using the bot.__\n\n"
        "**» /blocklist**\n"
        "    __List all blocked users.__\n\n"
        "**» /gban ; /ungban**\n"
        "    __Globally ban or unban user from using the bot.__\n\n"
        "**» /gbanlist**\n"
        "    __List all globally banned users.__\n\n"
        "**» /logs**\n"
        "    __Get the logs of the bot.__\n\n"
        "**» /restart**\n"
        "    __Restart the bot globally.__\n\n"
        "**» /sudolist**\n"
        "    __List all sudo users.__\n\n"
        "**» /stats**\n"
        "    __Show full stats of the bot.__\n\n"
    )
    HELP_OTHERS = (
        "**OTHER COMMANDS:**\n\n"
        "**» /start**\n"
        "    __Check if the bot is alive.__\n\n"
        "**» /ping**\n"
        "    __Check ping of the bot.__\n\n"
        "**» /help**\n"
        "    __Show this menu.__\n\n"
        "**» /sysinfo**\n"
        "    __Show system information of the bot.__\n\n"
        "**» /leaderboard ; /topusers**\n"
        "    __Show the top 10 users with most number of songs played.__\n\n"
    )
    HELP_OWNERS = (
        "**OWNER COMMANDS:**\n\n"
        "**» /eval ; /run**\n"
        "    __Execute the python script.__\n\n"
        "**» /exec ; /term ; /sh**\n"
        "    __Execute the bash script.__\n\n"
        "**» /getvar ; /gvar ; /var**\n"
        "    __Get the value of the config variable.__\n\n"
        "**» /addsudo**\n"
        "    __Add sudo user of the bot who can use sudo commands.__\n\n"
        "**» /rmsudo ; /delsudo**\n"
        "    __Remove sudo user of the bot.__\n\n"
        "**» /logs**\n"
        "    __Retrieve the bot's logs.__\n\n"
        "**» /gitpull**\n"
        "    __Update the bot with the latest changes from the repository.__\n\n"
        "**» /restart**\n"
        "    __Restart the bot.__\n\n"
    )
    HELP_GC = (
        "ɢᴇᴛ ᴛʜᴇ ʜᴇʟᴘ ᴍᴇɴᴜ ɪɴ ʏᴏᴜʀ ᴘᴍ. "
        "__ᴄʟɪᴄᴋ ᴛʜᴇ ʙᴜᴛᴛᴏɴ ʙᴇʟᴏᴡ!__"
    )
    HELP_PM = (
        "**ʜᴇʟᴘ ⚙️**\n\n"
        "__» ᴀʟʟ ᴄᴏᴍᴍᴀɴᴅs ᴀʀᴇ ᴄᴀᴛᴇɢᴏʀɪᴢᴇᴅ ʙᴀsᴇᴅ ᴏɴ ᴛʜᴇɪʀ ᴜsᴀʙɪʟɪᴛʏ ᴀɴᴅ ᴛᴀʀɢᴇᴛ ᴜsᴇʀs.__\n"
        "__» ʏᴏᴜ ᴄᴀɴ ᴜsᴇ ᴛʜᴇsᴇ ʙᴜᴛᴛᴏɴs ʙᴇʟᴏᴡ ᴛᴏ ɴᴀᴠɪɢᴀᴛᴇ ᴇᴀᴄʜ ᴄᴀᴛᴇɢᴏʀʏ ᴀɴᴅ ɢᴇᴛ ʀᴇsᴘᴇᴄᴛɪᴠᴇ ᴄᴏᴍᴍᴀɴᴅs.__\n"
        "__» ғᴇᴇʟ ғʀᴇᴇ ᴛᴏ ᴄᴏɴᴛᴀᴄᴛ ᴜs ɪғ ʏᴏᴜ ɴᴇᴇᴅ ᴀɴʏ ʜᴇʟᴘ ʀᴇɢᴀʀᴅɪɴɢ ᴛʜᴇ ʙᴏᴛ.__\n\n"
        "❤️🎶 {0}"
    )
    START_GC = (
        "ʜᴇʏ, ɪ'ᴍ ʀᴇᴀᴅʏ ᴛᴏ ʀᴏᴄᴋ! "
        "ʟᴇᴛ'ꜱ ɢᴇᴛ ᴛʜᴇ ᴍᴜꜱɪᴄ ꜱᴛᴀʀᴛᴇᴅ! 🎶"
    )
    START_PM = (
        "**Hello there** {0}**!**\n\n"
        "**I'm** {1} **,**\n"
        "➻ ᴀ ғᴀsᴛ & ᴘᴏᴡᴇʀғᴜʟ ᴛᴇʟᴇɢʀᴀᴍ ᴍᴜsɪᴄ ᴘʟᴀʏᴇʀ ʙᴏᴛ ᴡɪᴛʜ sᴏᴍᴇ ᴀᴡᴇsᴏᴍᴇ ғᴇᴀᴛᴜʀᴇs.\n"
        "•── ⋅ ⋅ ⋅ ────── ⋅  ⋅ ────── ⋅ ⋅ ⋅ ──•\n"
        "๏ ᴄʟɪᴄᴋ ᴏɴ ᴛʜᴇ ʜᴇʟᴩ ʙᴜᴛᴛᴏɴ ᴛᴏ ɢᴇᴛ ɪɴғᴏʀᴍᴀᴛɪᴏɴ ᴀʙᴏᴜᴛ ᴍʏ ᴍᴏᴅᴜʟᴇs ᴀɴᴅ ᴄᴏᴍᴍᴀɴᴅs.\n"
        "❤️🎶 @{2}"
    )
    PERFORMER = "[ ʙᴀᴅ ᴍᴜɴᴅᴀ ]"
